# uncompyle6 version 3.5.0
# Python bytecode 2.7 (62211)
# Decompiled from: Python 2.7.16 (default, Apr 17 2020, 18:29:03) 
# [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
# Embedded file name: ..\ERPAbstract\DefaultQueries.py
# Compiled at: 2016-07-25 10:54:32
DEFAULTQUERIES = {'listMOrdersSQL': "SELECT * FROM m_order WHERE sync_status ='N' and m_order_status in (%s);", 'listMOrderItemsSQL': "SELECT sku, qty, price, tax_amt FROM m_order_item WHERE m_order_id = '%s';", 
   'listMCancelOrdersSQL': "SELECT * FROM m_order\n                WHERE sync_status ='N'\n                and m_order_status = 'canceled';", 
   'listMDownPaymentsSQL': "SELECT e_order_inc_id, grand_total\n              FROM m_order\n              WHERE sync_status = 'O'\n              AND payment_method in ({paymentMethods})\n              AND m_order_status in ({mOrderStatus})\n              AND e_order_inc_id NOT IN (\n                SELECT e_order_inc_id\n                FROM e_downpayment\n                WHERE sync_status = 'O'\n              )\n  ", 
   'listMCustsSQL': "SELECT * FROM m_customer WHERE sync_status in ('N','F');", 
   'listMCustAddrsSQL': "SELECT * FROM m_customer_addr WHERE m_cust_id = '%s';", 
   'listMInvoicesSQL': "SELECT m_order_inc_id, m_invoice_inc_id, e_shipment_inc_id\n              FROM e_shipment\n              WHERE sync_status = 'O'\n              AND e_shipment_inc_id not in (\n                SELECT e_shipment_inc_id\n                FROM e_invoice\n                WHERE sync_status = 'O');", 
   'insertOrUpdateEProductSQL': 'INSERT INTO e_product_master\n              (sku,e_product_id,raw_data,sync_status,sync_dt,sync_notes)\n              VALUES\n              (%s,%s,%s,%s,NOW(),%s)\n              ON DUPLICATE KEY UPDATE\n              e_product_id = %s,\n              raw_data = %s,\n              sync_status = %s,\n              sync_notes = %s,\n              sync_dt = NOW()\n              ;', 
   'listNeedShipOrdersSQL': "\n            SELECT id, e_order_inc_id,m_order_inc_id, total_qty\n                    FROM m_order\n                    WHERE m_order_status IN ({mOrderStatus}) AND sync_status IN ('O','N')\n            ", 
   'listOrderExistingShipmentSQL': '\n            SELECT id,e_shipment_inc_id, m_order_inc_id, sync_status\n                  FROM e_shipment\n                  WHERE m_order_inc_id = %s\n      ', 
   'addOrUpdateEProductMasterSQL': '\n            INSERT INTO e_product_master\n                    (sku,e_product_id,raw_data,sync_status,sync_dt,sync_notes)\n                    VALUES\n                    (%s,%s,%s,%s,NOW(),%s)\n                    ON DUPLICATE KEY UPDATE\n                    e_product_id = %s,\n                    raw_data = %s,\n                    sync_status = %s,\n                    sync_notes = %s,\n                    sync_dt = NOW()\n  ', 
   'addOrUpdateEProductInventorySQL': '\n            INSERT INTO e_product_inventory\n                    (sku,website_code,qty,is_in_stock,stock_status,sync_status,sync_dt,sync_notes)\n                    VALUES\n                    (%s,%s,%s,%s,%s,%s,NOW(),%s)\n                    ON DUPLICATE KEY UPDATE\n                    qty = %s,\n                    is_in_stock = %s,\n            stock_status = %s,\n                    sync_status = %s,\n                    sync_notes = %s,\n                    sync_dt = NOW()\n  ', 
   'addOrUpdateEProductPriceSQL': '\n            INSERT INTO e_product_price\n                    (sku,website_code,store_code,price,special_price,special_from_date,special_to_date,sync_status,sync_dt,sync_notes)\n                    VALUES\n                    (%s,%s,%s,%s,%s,%s,%s,%s,NOW(),%s)\n                    ON DUPLICATE KEY UPDATE\n                    price = %s,\n                    special_price = %s,\n            special_from_date = %s,\n            special_to_date = %s,\n                    sync_status = %s,\n                    sync_notes = %s,\n                    sync_dt = NOW()\n  ', 
   'addOrUpdateEProductTierPriceSQL': '\n    INSERT INTO e_product_tier_price\n    (sku,all_groups,customer_group,qty,website_code,price,sync_status,sync_dt,sync_notes)\n    VALUES\n    (%s,%s,%s,%s,%s,%s,%s,NOW(),%s)\n    ON DUPLICATE KEY UPDATE\n    price = %s,\n    sync_status = %s,\n    sync_notes = %s,\n    sync_dt = NOW()\n  ', 
   'addOrUpdateEProductGroupPriceSQL': '\n    INSERT INTO e_product_group_price\n    (sku,all_groups,customer_group,website_code,price,sync_status,sync_dt,sync_notes)\n    VALUES\n    (%s,%s,%s,%s,%s,%s,NOW(),%s)\n    ON DUPLICATE KEY UPDATE\n    price = %s,\n    sync_status = %s,\n    sync_notes = %s,\n    sync_dt = NOW()\n  ', 
   'addOrUpdateECustomerSQL': '\n    INSERT INTO e_customer\n    (email,website_code,e_json_data,sync_status,sync_dt,sync_notes)\n    VALUES\n    (%s,%s,%s,%s,NOW(),%s)\n    ON DUPLICATE KEY UPDATE\n    e_json_data = %s,\n    sync_status = %s,\n    sync_notes = %s,\n    sync_dt = NOW()\n  ', 
   'addOrUpdateEConfigProductSQL': '\n            INSERT INTO e_config_product\n            (parent_sku,child_sku,raw_data,sync_status,sync_dt,sync_notes)\n            VALUES\n            (%s,%s,%s,%s,NOW(),%s)\n            ON DUPLICATE KEY UPDATE\n            raw_data = %s,\n            sync_status = %s,\n            sync_notes = %s,\n            sync_dt = NOW()\n  ', 
   'addOrUpdateEProductCompanyPriceSQL': '\n    INSERT INTO e_product_company_price\n    (sku,company_code,qty,website_code,price,sync_status,sync_dt,sync_notes)\n    VALUES\n    (%s,%s,%s,%s,%s,%s,NOW(),%s)\n    ON DUPLICATE KEY UPDATE\n    price = %s,\n    sync_status = %s,\n    sync_notes = %s,\n    sync_dt = NOW()\n  ', 
   'addOrUpdateEProductCategorySQL': '\n    INSERT IGNORE INTO e_product_category\n    (sku, path, store_code, action, create_at, sync_dt, sync_status, sync_notes)\n    VALUES\n    (%s,%s,%s,%s,now(),now(),%s,%s)\n  '}
# okay decompiling DefaultQueries.pyc
